// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    latest_region_status: {
        name: "latest_region_status";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          region_id: string;
          /** @sqlType TIMESTAMP */
          interval_end: string;
          /** @sqlType INT */
          intervention: number;
          /** @sqlType DOUBLE */
          rrp_aud_per_mwh: number;
          /** @sqlType DOUBLE */
          total_demand_mw: number;
          /** @sqlType TIMESTAMP */
          source_interval_watermark: string;
          /** @sqlType TIMESTAMP */
          source_publication_at: string;
          /** @sqlType TIMESTAMP */
          gold_published_at: string;
          /** @sqlType BIGINT */
          market_wide_binding_constraint_count: number;
          /** @sqlType BIGINT */
          market_wide_interconnector_count: number;
          /** @sqlType DOUBLE */
          market_wide_interconnector_source_sign_flow_mw: number;
          /** @sqlType DOUBLE */
          prediction_score: number;
          /** @sqlType STRING */
          prediction_model_version: string;
          /** @sqlType TIMESTAMP */
          prediction_feature_time: string;
          /** @sqlType TIMESTAMP */
          prediction_scored_at: string;
          /** @sqlType STRING */
          prediction_source_freshness: string;
          /** @sqlType STRING */
          prediction_missing_feature_status: string;
        }>;
      };
  }
}
