// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    latest_fuel_generation: {
        name: "latest_fuel_generation";
        parameters: {
          /** STRING - use sql.string() */
          fuel_generation_table: SQLStringMarker;
        };
        result: unknown;
      };
    latest_region_status: {
        name: "latest_region_status";
        parameters: {
          /** STRING - use sql.string() */
          region_status_table: SQLStringMarker;
        };
        result: unknown;
      };
    latest_unit_dispatch: {
        name: "latest_unit_dispatch";
        parameters: Record<string, never>;
        result: unknown;
      };
  }
}
